server:
  port: 3344
spring:
  application:
    name: springcloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SandRainD/springcloud-config.git
          search-paths:
            - springcluod-config
          ignore-local-ssh-settings: true
      label: main
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'