server:
  port: 80

spring:
  application:
    name: springcloud-order-consul

  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        service-name: ${spring.application.name}