server:
  port: 9527
spring:
  application:
    name: springcloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh #路由的id，要求唯一建议配合服务名
#          uri: http://localhost:8001 #匹配后提供的服务地址
          uri: lb://springcloud-payment
          predicates:
            - Path=/payment/get/** #断言，路径相匹配进行路由
            - After=2021-12-29T18:04:37.905+08:00[Asia/Shanghai]
        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://springcloud-payment
          predicates:
            - Path=/payment/lb/**
      discovery:
        locator:
          enabled: true  #开启从注册中心动态生成路由的功能，用微服务名进行路由

eureka:
  instance:
    hostname: springcloud_gateway_service
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    register-with-eureka: true
    fetch-registry: true